obj-n += dummy.o
obj-$(CONFIG_SIMUL_AVR) += simulavr.o
obj-$(CONFIG_IRQ_SUPPORT) += irq.o
obj-$(CONFIG_TIMER) += time.o
obj-$(CONFIG_SCHED) += sched.o context.o
obj-y += spinlock.o cpu.o
extra-y += start.o init.o
