obj-y += stress.o eeprom.o sram.o
pyusrlib-y += main.py
crurom-y := data
crurom-obj := romfs.o

ETAOS_LIBS += -l24c02 -leeprom -latmega-i2c -li2c-core -latmega-gpio -lgpio \
		-lusart-atmega -lusart1-atmega -lusart -lspi-core -latmega-spi \
		-lsram -l23k256 -latmega-analog -lanalog -latmega-flash -lflash \
		-ldevfs -ldriver-core -lplatform -llm35 -lpwm-core -latmega-pwm -lc
ETAOS_LIB_DIR := usr/lib/etaos
APP_TARGET := test-app.img
clean-files += test-app.img test-app.hex romfs.c pyusrlib.c pyusrlib-img.c
