obj-y += eeprom.o
ETAOS_LIBS += -l24c02 -latmega-i2c -li2c-core -lusart-atmega \
		-lusart -ldriver-core -lc
ETAOS_LIB_DIR := /usr/lib/etaos
APP_TARGET := test-app.img
clean-files += test-app.img test-app.hex
