obj-y += init.o sys.o delay.o panic.o cpu.o
obj-$(CONFIG_HARVARD) += panic_P.o
obj-$(CONFIG_CPP) += cplusplus.o
obj-$(CONFIG_SEM) += semaphore.o
obj-$(CONFIG_MUTEX_EVENT_QUEUE) += mutex.o
obj-$(CONFIG_IRQ_SUPPORT) += irq/
obj-$(CONFIG_TIMER) += time/
obj-$(CONFIG_SCHED) += sched/
