obj-y += init.o sys.o delay.o panic.o cpu.o spinlock.o
obj-$(CONFIG_HARVARD) += panic_P.o
obj-$(CONFIG_CPP) += cplusplus.o
obj-$(CONFIG_IRQ_SUPPORT) += irq/
obj-$(CONFIG_TIMER) += time/
obj-$(CONFIG_SCHED) += sched/
