obj-$(CONFIG_VFS) += virtualfs.o
obj-$(CONFIG_ROMFS) += romfs.o
obj-$(CONFIG_DEVFS) += devfs.o
obj-$(CONFIG_RAMFS) += ramfs.o

virtualfs-y = vfs.o read_write.o fops.o close.o open.o dirent.o basename.o
virtualfs-y += util.o open_close.o
