obj-y += cplusplus.o
ETAOS_LIBS += -l24c02 -leeprom -li2c-core -latmega-i2c -lsram -l23k256 \
		-latmega-spi -lspi-core \
		-latmega-gpio -lgpio \
		-lusart-atmega -lusart -latmega-analog -lanalog \
		-ldriver-core -lplatform -letaos -lc
ETAOS_LIB_DIR := usr/lib/etaos
APP_TARGET := test-app.img
clean-files += test-app.img test-app.hex
