obj-$(CONFIG_SCHED)		+= core.o algo.o thread.o
obj-$(CONFIG_IPM)		+= ipm.o
obj-$(CONFIG_EVENT_MUTEX)	+= evm.o

algo-$(CONFIG_RR)		+= rr.o
algo-$(CONFIG_RR_SHARED)	+= rr-shared.o
algo-$(CONFIG_FIFO)		+= fifo.o
algo-$(CONFIG_LOTTERY)		+= lottery.o
