obj-$(CONFIG_SCHED)		+= sched.o algo.o
obj-$(CONFIG_IPM)		+= ipm.o
obj-$(CONFIG_EVENT_MUTEX)	+= event.o
obj-$(CONFIG_MUTEX_EVENT_QUEUE) += mutex.o
obj-$(CONFIG_SEM)               += semaphore.o

algo-$(CONFIG_RR)		+= rr.o
algo-$(CONFIG_RR_SHARED)	+= rr-shared.o
algo-$(CONFIG_FIFO)		+= fifo.o
algo-$(CONFIG_LOTTERY)		+= lottery.o
algo-$(CONFIG_EDF)		+= edf.o

sched-y = core.o clock.o thread.o
