obj-y += stress.o eeprom.o sram.o
crurom-y := data
crurom-obj := romfs.o

ETAOS_LIBS += -l24c02 -leeprom -latmega-i2c -li2c-core -latmega-gpio -lgpio \
		-lusart-atmega -lusart -lspidev -latmega-spi \
		-lsram -l23k256 -latmega-analog -lanalog \
		-ldriver-core -lc
ETAOS_LIB_DIR := /usr/lib/etaos
APP_TARGET := test-app.img
clean-files += test-app.img test-app.hex romfs.c
